on:
  push:
    branches:
      - master

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.7.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: multi-gitter
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"dep","section":"Dependencies","hidden":false}]'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.0"
        if: ${{ steps.release.outputs.release_created }}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.JENKINS_INFRA_HELPDESK_APP_ID }}
          private_key: ${{ secrets.JENKINS_INFRA_HELPDESK_APP_PRIVATE_KEY }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }} # Gemfury token
        if: ${{ steps.release.outputs.release_created }}

      - name: Comment on prs and issues
        uses: apexskier/github-release-commenter@v1.3.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template:
            Included in release {release_link} 🎉
          skip-label: "autorelease: tagged,autorelease: pending"
        if: ${{ steps.release.outputs.release_created }}
